### ISSUE TITLE
Exception when minifying JS, no output

### ISSUE THREAD

**Issue by vallieresc** [Chris2011/js-css-minify-compress#25]
I'm attemping to minify my jquery script that is working flawlessly. It contains no errors and is based on the jquery plugin boilerplate. When clicking "Minify JS", I get a success message but the min.js file is empty. I have a notification about an exception from the plugin:

org.mozilla.javascript.EvaluatorException: Compilation produced 13 syntax errors.
    at org.netbeans.util.source.minify.MinifyUtil$CompressorErrorReporter.runtimeError(MinifyUtil.java:485)
    at org.mozilla.javascript.Parser.parse(Parser.java:392)
    at org.mozilla.javascript.Parser.parse(Parser.java:337)
    at com.yahoo.platform.yui.compressor.JavaScriptCompressor.parse(JavaScriptCompressor.java:312)
    at com.yahoo.platform.yui.compressor.JavaScriptCompressor.<init>(JavaScriptCompressor.java:533)
    at org.netbeans.util.source.minify.MinifyUtil.compress(MinifyUtil.java:371)
    at org.netbeans.util.source.minify.JSMinify.jsMinify(JSMinify.java:99)
    at org.netbeans.util.source.minify.JSMinify.access$000(JSMinify.java:47)
    at org.netbeans.util.source.minify.JSMinify$1.run(JSMinify.java:65)
    at org.openide.util.RequestProcessor$Task.run(Unknown Source)
    at org.netbeans.modules.openide.util.GlobalLookup.execute(Unknown Source)
    at org.openide.util.lookup.Lookups.executeWith(Unknown Source)
    at org.openide.util.RequestProcessor$Processor.run(Unknown Source)

Also, I was able to minify my JS with an online minifier.

**Comment by friend8** [comment]
Seems like this is the same problem as described in #3

**Comment by Chris2011** [comment]
If it has ES6 support inside the file, please attach a sample file, then it is a problem, which was described in #3 as @friend8 said.
