### ISSUE TITLE
JS minification not working for some files (exception output)

### ISSUE THREAD

**Issue by anchev** [Chris2011/js-css-minify-compress#27]
I have a JS file which cannot be minified. The .min.js output is an empty file. Additionally Netbeans 8.2 outputs this exception:

```
org.mozilla.javascript.EvaluatorException: Compilation produced 4 syntax errors.
	at org.netbeans.util.source.minify.MinifyUtil$CompressorErrorReporter.runtimeError(MinifyUtil.java:485)
	at org.mozilla.javascript.Parser.parse(Parser.java:392)
	at org.mozilla.javascript.Parser.parse(Parser.java:337)
	at com.yahoo.platform.yui.compressor.JavaScriptCompressor.parse(JavaScriptCompressor.java:312)
	at com.yahoo.platform.yui.compressor.JavaScriptCompressor.<init>(JavaScriptCompressor.java:533)
	at org.netbeans.util.source.minify.MinifyUtil.compress(MinifyUtil.java:371)
	at org.netbeans.util.source.minify.JSMinify.jsMinify(JSMinify.java:99)
	at org.netbeans.util.source.minify.JSMinify.access$000(JSMinify.java:47)
	at org.netbeans.util.source.minify.JSMinify$1.run(JSMinify.java:65)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)
```

The JS file is valid and free of errors. I have been able to minify it with other tools:

```
$(function () {

//        ...
    function f(x, y=false) {
        // ...
    }

//        ...
});
```

If I remove the "= false" part it minifies successfully.

**Comment by friend8** [comment]
Same problem here.
The following file won't be minified: https://github.com/friend8/DSA-Blacksmith/blob/master/lib/js/crafting.js
But this file is minified without problems: https://github.com/friend8/DSA-Blacksmith/blob/master/lib/js/blueprint.js

This problem occured in Netbeans 8.2, 8.1 and 8.0.2

> org.mozilla.javascript.EvaluatorException: Compilation produced 15 syntax errors.
> 	at org.netbeans.util.source.minify.MinifyUtil$CompressorErrorReporter.runtimeError(MinifyUtil.java:464)
> 	at org.mozilla.javascript.Parser.parse(Parser.java:392)
> 	at org.mozilla.javascript.Parser.parse(Parser.java:337)
> 	at com.yahoo.platform.yui.compressor.JavaScriptCompressor.parse(JavaScriptCompressor.java:312)
> 	at com.yahoo.platform.yui.compressor.JavaScriptCompressor.<init>(JavaScriptCompressor.java:533)
> 	at org.netbeans.util.source.minify.MinifyUtil.compress(MinifyUtil.java:350)
> 	at org.netbeans.util.source.minify.JSMinify.jsMinify(JSMinify.java:99)
> 	at org.netbeans.util.source.minify.JSMinify.access$000(JSMinify.java:47)
> 	at org.netbeans.util.source.minify.JSMinify$1.run(JSMinify.java:65)
> 	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
> 	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)

**Comment by anchev** [comment]
Maybe ECMAScript 6 is not supported.

**Comment by Chris2011** [comment]
Maybe I can have a look later to update the yui compressor. Hope that this will fix the problem

**Comment by Chris2011** [comment]
There is a bug open about this: https://github.com/yui/yuicompressor/issues/262 maybe this is the problem.

**Comment by anchev** [comment]
Maybe. Meanwhile I started using Clouldflare which minifies everything in real time :) Sites can't wait.

**Comment by Chris2011** [comment]
Yeah unfortunately I can't do anything here, except fixing the yui compressor and I won't do it. It is a ES6 problem and was original handled here #3.
