### ISSUE TITLE
org.mozilla.javascript.EvaluatorException: Compilation produced 18 syntax errors.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Chris2011/js-css-minify-compress#3]
```
This issue was originally reported against NetBeans, for details please see [1] 
and [2]


org.mozilla.javascript.EvaluatorException: Compilation produced 18 syntax 
errors.
   at org.netbeans.util.source.minify.MinifyUtil$CompressorErrorReporter.runtimeError(MinifyUtil.java:366)
   at org.mozilla.javascript.Parser.parse(Parser.java:392)
   at org.mozilla.javascript.Parser.parse(Parser.java:337)
   at com.yahoo.platform.yui.compressor.JavaScriptCompressor.parse(JavaScriptCompressor.java:312)
   at com.yahoo.platform.yui.compressor.JavaScriptCompressor.<init>(JavaScriptCompressor.java:533)
   at org.netbeans.util.source.minify.MinifyUtil.compressJavaScript(MinifyUtil.java:161)
   at org.netbeans.util.source.minify.JSMinify.jsMinify(JSMinify.java:91)
   at org.netbeans.util.source.minify.JSMinify$1.run(JSMinify.java:61)
   at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
   at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)



[1] https://netbeans.org/bugzilla/show_bug.cgi?id=243608
[2] http://statistics.netbeans.org/exceptions/detail.do?id=205000

```

Original issue reported on code.google.com by `riha.vla...@gmail.com` on 6 Jun 2014 at 8:23

**Comment by Chris2011** [comment]
Wontfix means, that I don't fix smth here, because it is an external problem with the used yui compressor lib.

**Comment by hkaraoglu** [comment]
At least , the plugin shouldn't output empty file. Because it causes error.

**Comment by Chris2011** [comment]
I can check it but the output file comes from thr yuicompressor afaik.

**Comment by hkaraoglu** [comment]
If file is empty, (so, compressor throws error) the output file is filled with orginal data.

**Comment by Chris2011** [comment]
ATM the plugin is not on my prio list, I'm waiting for the ES6 support or YUICompressor, so if you think there could be a better behaviour than now, a PR is much appreciated.

**Comment by hkaraoglu** [comment]
What is ATM? 
You can check created minifed file , if it is empty, can you delete file?

**Comment by Chris2011** [comment]
ATM means at the moment. There is more todo like a message that file wasn't created in case of errors.
