### ISSUE TITLE
Javascript object error with variable named 'short'

### ISSUE THREAD

**Issue by qrczakoff** [Chris2011/js-css-minify-compress#30]
When I have object with variable named 'short', minified file is empty:
var test = {
    variable: 'foo',
    short: 'bar'
} // empty file.

var test = {
    variable: 'foo',
//    short: 'bar'
} // file OK.

**Comment by Chris2011** [comment]
This is a problem of the YUICompressor. It will throw this exception:

```
[ERROR] in -
  3:6:invalid property id
[ERROR] in -
  3:7:syntax error
[ERROR] in -
  1:0:Compilation produced 2 syntax errors.
org.mozilla.javascript.EvaluatorException: Compilation produced 2 syntax errors.
	at com.yahoo.platform.yui.compressor.YUICompressor$1.runtimeError(YUICompressor.java:172)
	at org.mozilla.javascript.Parser.parse(Parser.java:396)
	at org.mozilla.javascript.Parser.parse(Parser.java:340)
	at com.yahoo.platform.yui.compressor.JavaScriptCompressor.parse(JavaScriptCompressor.java:315)
	at com.yahoo.platform.yui.compressor.JavaScriptCompressor.<init>(JavaScriptCompressor.java:536)
	at com.yahoo.platform.yui.compressor.YUICompressor.main(YUICompressor.java:147)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.yahoo.platform.yui.compressor.Bootstrap.main(Bootstrap.java:21)
```

you can try it here: http://refresh-sf.com/

**Comment by Chris2011** [comment]
Tested with the new verison 2.3.0, which is using Google Closure Compiler. Will release it soon.
